### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by SarnaxLii** [TAG-Epic/TAG-Epic#1]
HELLO , ACCEPT FRIEND FAIL PLEASE ADD DISCORD ME BACK 👍🏻 

Discord : Sarnax#7522
![favicon-removebg-preview](https://user-images.githubusercontent.com/94861415/176513848-8b17032e-89db-4a4f-8e32-95a84a8264bc.png)

Sarnax & Trust

**Comment by EmreTech** [comment]
Why...
